<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>SmartPOS.Reporting</RootNamespace>
    <AssemblyName>SmartPOS.Reporting</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="QuestPDF" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SmartPOS.Application\SmartPOS.Application.csproj" />
    <ProjectReference Include="..\SmartPOS.Infrastructure\SmartPOS.Infrastructure.csproj" />
    <ProjectReference Include="..\SmartPOS.Shared\SmartPOS.Shared.csproj" />
  </ItemGroup>
</Project>
